# Form implementation generated from reading ui file 'ins_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets

from PyQt6.QtWidgets import QApplication, QMainWindow,  QLabel, QPushButton, QTextEdit, QMdiSubWindow, QMdiArea, QDialog, QMessageBox ,QLineEdit, QPlainTextEdit ,QComboBox, QTableView 
#from PyQt6.QtGui import QAction, QKeySequence, QKeyEvent, QShortcut, QIntValidator 
#from PyQt6.QtSql import QSqlDatabase, QSqlTableModel
from PyQt6.QtCore import Qt, QSortFilterProxyModel
from PyQt6 import uic 
from PyQt6.QtGui import QStandardItemModel, QStandardItem
import psycopg2
from connect_database import ConnectDatabase

import dash_ag_grid as dag
import pandas as pd


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(926, 606)
        self.c_tableView = QtWidgets.QTableView(parent=Dialog)
        self.c_tableView.setGeometry(QtCore.QRect(9, 300, 921, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c_tableView.sizePolicy().hasHeightForWidth())
        self.c_tableView.setSizePolicy(sizePolicy)
        self.c_tableView.setObjectName("c_tableView")
        self.frame_2 = QtWidgets.QFrame(parent=Dialog)
        self.frame_2.setGeometry(QtCore.QRect(2, 210, 920, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_13 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(9, 2, 121, 16))
        self.label_13.setObjectName("label_13")
        self.c_description_plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.frame_2)
        self.c_description_plainTextEdit.setGeometry(QtCore.QRect(10, 20, 900, 60))
        self.c_description_plainTextEdit.setObjectName("c_description_plainTextEdit")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(9, 10, 921, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(240, 10, 61, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_11 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.layoutWidget_3 = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget_3.setGeometry(QtCore.QRect(444, 13, 89, 171))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.layoutWidget_4 = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget_4.setGeometry(QtCore.QRect(33, 10, 63, 171))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget_4)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label = QtWidgets.QLabel(parent=self.layoutWidget_4)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget_4)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.layoutWidget_5 = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget_5.setGeometry(QtCore.QRect(94, 11, 131, 181))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.c_productcode_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        self.c_productcode_lineEdit.setObjectName("c_productcode_lineEdit")
        self.verticalLayout_6.addWidget(self.c_productcode_lineEdit)
        self.c_season_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        self.c_season_lineEdit.setObjectName("c_season_lineEdit")
        self.verticalLayout_6.addWidget(self.c_season_lineEdit)
        self.c_brand_comboBox = QtWidgets.QComboBox(parent=self.layoutWidget_5)
        self.c_brand_comboBox.setObjectName("c_brand_comboBox")
        #self.c_brand_comboBox.addItem("")
        #self.c_brand_comboBox.setItemText(0, "")
        #self.c_brand_comboBox.addItem("")
        #self.c_brand_comboBox.addItem("")
        #self.c_brand_comboBox.addItem("")
        self.verticalLayout_6.addWidget(self.c_brand_comboBox)
        self.c_quantity_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        self.c_quantity_lineEdit.setObjectName("c_quantity_lineEdit")
        self.verticalLayout_6.addWidget(self.c_quantity_lineEdit)
        self.layoutWidget_6 = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget_6.setGeometry(QtCore.QRect(533, 11, 131, 181))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.c_sale_price_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_6)
        self.c_sale_price_lineEdit.setObjectName("c_sale_price_lineEdit")
        self.verticalLayout_7.addWidget(self.c_sale_price_lineEdit)
        self.c_buying_price_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_6)
        self.c_buying_price_lineEdit.setObjectName("c_buying_price_lineEdit")
        self.verticalLayout_7.addWidget(self.c_buying_price_lineEdit)
        self.c_price_per_unit_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_6)
        self.c_price_per_unit_lineEdit.setObjectName("c_price_per_unit_lineEdit")
        self.verticalLayout_7.addWidget(self.c_price_per_unit_lineEdit)
        self.c_gross_profit_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_6)
        self.c_gross_profit_lineEdit.setObjectName("c_gross_profit_lineEdit")
        self.verticalLayout_7.addWidget(self.c_gross_profit_lineEdit)
        self.c_tax_percentage_lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.c_tax_percentage_lineEdit.setGeometry(QtCore.QRect(762, 24, 129, 26))
        self.c_tax_percentage_lineEdit.setText("")
        self.c_tax_percentage_lineEdit.setObjectName("c_tax_percentage_lineEdit")
        self.layoutWidget_7 = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget_7.setGeometry(QtCore.QRect(301, 10, 131, 181))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.c_pname_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_7)
        self.c_pname_lineEdit.setObjectName("c_pname_lineEdit")
        self.verticalLayout_5.addWidget(self.c_pname_lineEdit)
        self.c_size_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_7)
        self.c_size_lineEdit.setObjectName("c_size_lineEdit")
        self.verticalLayout_5.addWidget(self.c_size_lineEdit)
        self.c_material_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_7)
        self.c_material_lineEdit.setObjectName("c_material_lineEdit")
        self.verticalLayout_5.addWidget(self.c_material_lineEdit)
        self.c_color_lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget_7)
        self.c_color_lineEdit.setObjectName("c_color_lineEdit")
        self.verticalLayout_5.addWidget(self.c_color_lineEdit)
        self.c_add_pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.c_add_pushButton.setGeometry(QtCore.QRect(750, 140, 131, 31))
        self.c_add_pushButton.setObjectName("c_add_pushButton")
        self.label_14 = QtWidgets.QLabel(parent=self.frame)
        self.label_14.setGeometry(QtCore.QRect(682, 25, 36, 20))
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        #self.c_brand_lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        #self.c_brand_lineEdit.setGeometry(QtCore.QRect(760, 90, 129, 22))
        #self.c_brand_lineEdit.setObjectName("c_brand_lineEdit")
        
        self.c_table_update()#brand_filter='Canguro'
        self.load_existing_brands()
        self.init_signal_slot()
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Εισαγωγή στοιχείων"))
        self.label_13.setText(_translate("Dialog", "Παρατηρήσεις :"))
        self.label_5.setText(_translate("Dialog", "Όνομα"))
        self.label_11.setText(_translate("Dialog", "Size"))
        self.label_12.setText(_translate("Dialog", "Υλικό"))
        self.label_2.setText(_translate("Dialog", "*Χρώμα"))
        self.label_3.setText(_translate("Dialog", "*Τιμή πώλησης"))
        self.label_6.setText(_translate("Dialog", "*Τιμή αγοράς"))
        self.label_7.setText(_translate("Dialog", "Συνολικό κόστος"))
        self.label_8.setText(_translate("Dialog", "Μεικτό κέρδος"))
        self.label_4.setText(_translate("Dialog", "*Κωδικός"))
        self.label_10.setText(_translate("Dialog", "*Season"))
        self.label.setText(_translate("Dialog", "*Brand"))
        self.label_9.setText(_translate("Dialog", "*Ποσότητα"))
        #self.c_brand_comboBox.setItemText(1, _translate("Dialog", "Canguro"))
        #self.c_brand_comboBox.setItemText(2, _translate("Dialog", "Flivver"))
        #self.c_brand_comboBox.setItemText(3, _translate("Dialog", "Marina Militare"))
        self.c_add_pushButton.setText(_translate("Dialog", "Εισαγωγή"))
        self.label_14.setText(_translate("Dialog", "Φόρος"))

    def init_signal_slot(self):
        print("init_signal_slot")
        if self.c_add_pushButton.isChecked():
            print("Το κουμπί είναι ενεργό (checked)")
        else:
            print("Το κουμπί είναι ανενεργό (unchecked)")
        
        self.c_add_pushButton.clicked.connect(self.c_product_info)
        
        print("Η σύνδεση του κουμπιού με τη μέθοδο έγινε σωστά.")

    def get_c_product_info(self):
        print("get_c_product_info")
        # Function to retrieve product information from the form
        c_productcode = self.c_productcode_lineEdit.text().strip()
        c_pname = self.c_pname_lineEdit.text().strip()
        c_material = self.c_material_lineEdit.text().strip()
        c_color = self.c_color_lineEdit.text().strip()
        c_size = self.c_size_lineEdit.text().strip()
        c_seasons = self.c_season_lineEdit.text().strip()
        c_description = self.c_description_plainTextEdit.toPlainText().strip()
        #c_buying_price = float(self.c_buying_price.text().strip()) if self.c_buying_price.text().strip() else None
        c_buying_price = self.c_buying_price_lineEdit.text().strip()
        c_sale_price = self.c_sale_price_lineEdit.text().strip()
        c_gross_profit = self.c_gross_profit_lineEdit.text().strip()
        c_price_per_unit = self.c_price_per_unit_lineEdit.text().strip()
        c_quantity = self.c_quantity_lineEdit.text().strip()
        c_tax_percentage = self.c_tax_percentage_lineEdit.text().strip()
        c_brand_comboBox = self.c_brand_comboBox.currentText()
        
        product_info = {
            "c_productcode": c_productcode,
            "c_pname": c_pname,  
            "c_size": c_size,
            "c_material": c_material,
            "c_color": c_color,
            "c_seasons": c_seasons,
            "c_description": c_description,
            "c_buying_price": c_buying_price,
            "c_sale_price": c_sale_price,
            "c_gross_profit": c_gross_profit,
            "c_price_per_unit": c_price_per_unit,
            "c_quantity": c_quantity,
            "c_tax_percentage": c_tax_percentage,
            "c_brand_comboBox": c_brand_comboBox
            }
        
        return product_info

    def c_product_info(self):
        #print("c_product_info")
        #self.enable_buttons()
        #self.add_btn.setDisabled(True)
        product_info = self.get_c_product_info()
        print("Product Info:", product_info)
        
        self.db = ConnectDatabase()
        
        if  not product_info["c_productcode"].strip():
            #QMessageBox.warning(self, "Invalid Input", "Product Code must be a valid Text.", QMessageBox.StandardButton.Ok)
            #QMessageBox.warning(self.parent(), "Invalid Input", "Product Code must be a valid Text.", QMessageBox.StandardButton.Ok)
            QMessageBox.warning(None, "Invalid Input", "Product Code must be a valid Text.", QMessageBox.StandardButton.Ok)
            return
        
        if   not product_info["c_seasons"].strip():
            QMessageBox.warning(None, "Invalid Input", "Seasons must be a valid integer.", QMessageBox.StandardButton.Ok)
            return
        
        elif self.c_brand_comboBox.currentText().strip() == "" or self.c_brand_comboBox.count() == 0:
            QMessageBox.warning(None, "Invalid Input", "Brand  must be a valid integer.", QMessageBox.StandardButton.Ok)
            return
        
        elif not product_info["c_quantity"].isdigit():
            QMessageBox.warning(None, "Invalid Input", "Quantity  must be a valid integer.", QMessageBox.StandardButton.Ok)
            return
        
        elif not product_info["c_color"].strip():
            QMessageBox.warning(None, "Invalid Input", "Color  must be a valid Color!.", QMessageBox.StandardButton.Ok)
            return
        elif not product_info["c_sale_price"].isdigit():
            QMessageBox.warning(None, "Invalid Input", "Sale price must be a valid integer.", QMessageBox.StandardButton.Ok)
            return
        
        elif not product_info["c_buying_price"].isdigit():
            QMessageBox.warning(None, "Invalid Input", "Buying price must be a valid integer.", QMessageBox.StandardButton.Ok)
            return
        success = False
        try:
            # Insert product info into the database     
            if product_info["c_productcode"] and product_info["c_brand_comboBox"] is not None and product_info ["c_seasons"] and product_info ["c_quantity"] and product_info ["c_sale_price"] and product_info ["c_buying_price"] and product_info ["c_color"]:
                print("Inserting product info into the database...")
                add_result = self.db.product_insert(c_productcode=product_info["c_productcode"],
                                                    c_pname=product_info["c_pname"],
                                                    c_size=product_info["c_size"],
                                                    c_material=product_info["c_material"],
                                                    c_color=product_info["c_color"],
                                                    #c_brand=product_info["c_brand"],
                                                    c_brand_comboBox=product_info["c_brand_comboBox"],
                                                    c_seasons=product_info["c_seasons"],
                                                    c_description=product_info["c_description"],
                                                    c_buying_price=product_info["c_buying_price"],
                                                    c_sale_price=product_info["c_sale_price"],
                                                    c_gross_profit = None if self.c_gross_profit_lineEdit.text().strip() == '' else float(self.c_gross_profit_lineEdit.text().strip()) ,
                                                    c_price_per_unit = None if self.c_price_per_unit_lineEdit.text().strip() == '' else float(self.c_price_per_unit_lineEdit.text().strip()),
                                                    c_quantity=product_info["c_quantity"],
                                                    c_tax_percentage = None if self.c_tax_percentage_lineEdit.text().strip() == '' else float(self.c_tax_percentage_lineEdit.text().strip())
                                                    )
                if add_result == "Duplicate Product Code":
                    success = False
                else:
                    success = True
            if success:
                self.clear_fields()                                        
                                                    
        except psycopg2.errors.UniqueViolation as e:
            self.db.connection.rollback()  # Rollback the transaction on duplicate error
            print("Unique constraint violation detected. Error:", e)  # Debugging print

            # Display message box for duplicate key error
            QMessageBox.warning(
                self, 
                "Duplicate Product Code", 
                f"Product code ({product_info['c_productcode']}) already exists. Please use a different product code.", 
                QMessageBox.StandardButton.Ok
            )
            #self.add_btn.setDisabled(False)
        except psycopg2.IntegrityError as e:
            self.db.connection.rollback()  # Rollback the transaction in case of a general IntegrityError
            error_message = str(e)
            print("IntegrityError detected:", error_message)  # Debugging print

            QMessageBox.warning(
                self, 
                "Insert Failed", 
                f"Insert failed due to a database constraint: {error_message}", 
                QMessageBox.StandardButton.Ok
            )
            #self.add_btn.setDisabled(False)
        except Exception as e:
            #self.db.connection.rollback()  # Rollback the transaction in case of other unexpected errors
            # Handle any other unexpected errors
            print("An unexpected error occurred:", e)  # Debugging print
            QMessageBox.critical(None, "Database Error", "An unexpected error occurred: {}".format(str(e)))

        self.c_table_update()#brand_filter=product_info["c_brand_comboBox"]

        return product_info

    def c_table_update(self, brand_filter=None):
        try:
            #print("c_table_update")
            self.db = ConnectDatabase()
            #print("Updating table...")
            data = self.db.tabel_insert_view()  # brand_filter brand_filter='Canguro'
            #print("Data for table update:", data)
            if data is None:
                print("No data returned from database")
                return
            # Δημιουργία μοντέλου
            self.model = QStandardItemModel()
            self.model.setHorizontalHeaderLabels(["ID" ,"Product Code", "Name", "Color", "Brand", "Seasons", "Size", "Material", "Description", "Buying Price", "Sale Price", "Gross Profit", "Price Per Unit", "Quantity", "Tax Percentage", "creation date"])

            for row in data:
                items = [QStandardItem(str(item)) for item in row]
                self.model.appendRow(items)

            self.proxy_model = QSortFilterProxyModel()
            self.proxy_model.setSourceModel(self.model)
            self.proxy_model.setFilterCaseSensitivity(QtCore.Qt.CaseSensitivity.CaseInsensitive)
            if hasattr(self, 'c_tableView'):
                self.c_tableView.setModel(self.proxy_model)
                self.c_tableView.setSortingEnabled(True)

                # Προαιρετικά: Ρύθμιση μεγέθους στηλών
                for column in range(self.model.columnCount()):
                    self.c_tableView.resizeColumnToContents(column)
            else:
                print("c_tableView not found")

        except Exception as e:
            print(f"Error in del_table_update: {str(e)}")
            QMessageBox.critical(self, "Error", f"Failed to update table: {str(e)}")
        ##print("c_table_update")
        #self.db = ConnectDatabase()
        ##print("Updating table...")
        #data = self.db.tabel_insert_view()  # brand_filter brand_filter='Canguro'
        ##print("Data for table update:", data)
        #
        ## Δημιουργία μοντέλου
        #self.model = QStandardItemModel()
        #self.model.setHorizontalHeaderLabels(["ID" ,"Product Code", "Name", "Color", "Brand", "Seasons", "Size", "Material", "Description", "Buying Price", "Sale Price", "Gross Profit", "Price Per Unit", "Quantity", "Tax Percentage", "creation date"])
        #
        #for row in data:
        #    items = [QStandardItem(str(item)) for item in row]
        #    self.model.appendRow(items)
        #
        #self.proxy_model = QSortFilterProxyModel()
        #self.proxy_model.setSourceModel(self.model)
        #self.proxy_model.setFilterCaseSensitivity(QtCore.Qt.CaseSensitivity.CaseInsensitive)

        #self.c_tableView.setModel(self.proxy_model)
        #self.c_tableView.setSortingEnabled(True)  # Ενεργοποίηση ταξινόμησης

    def load_existing_brands(self):
            try:
                self.db = ConnectDatabase()
                with self.db.conn.cursor() as cursor:
                    #cursor.execute("SELECT DISTINCT brand FROM product WHERE brand IS NOT NULL ORDER BY brand")
                    cursor.execute("SELECT DISTINCT brand_name FROM brands WHERE brand_name IS NOT NULL AND active = True ORDER BY brand_name")
                    brands = cursor.fetchall()
                    self.c_brand_comboBox.clear()
                    for brand in brands:
                        self.c_brand_comboBox.addItem(brand[0])
            except Exception as e:
                QMessageBox.warning(self, "Σφάλμα", f"Σφάλμα κατά τη φόρτωση των μαρκών: {str(e)}")

    def clear_fields(self):
        self.c_productcode_lineEdit.clear()
        self.c_pname_lineEdit.clear()
        self.c_size_lineEdit.clear()
        self.c_material_lineEdit.clear()
        self.c_color_lineEdit.clear()
        #self.c_brand_lineEdit.clear()
        self.c_season_lineEdit.clear()
        self.c_quantity_lineEdit.clear()
        self.c_buying_price_lineEdit.clear()
        self.c_sale_price_lineEdit.clear()
        self.c_gross_profit_lineEdit.clear()
        self.c_price_per_unit_lineEdit.clear()
        self.c_tax_percentage_lineEdit.clear()
        self.c_description_plainTextEdit.clear()
        self.c_brand_comboBox.setCurrentIndex(0)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
